# Используем официальный образ Go
FROM golang:1.25-alpine AS builder

# Устанавливаем зависимости
RUN apk add --no-cache git

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы проекта
COPY go.mod go.sum ./
COPY proto/ proto/
COPY gen/ gen/
COPY cmd/client/main.go cmd/client/main.go

# Скачиваем зависимости
RUN go mod download

# Собираем приложение
RUN CGO_ENABLED=0 GOOS=linux go build -o /client cmd/client/main.go

# Используем легкий образ для финального изображения
FROM alpine:latest

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем собранное приложение
COPY --from=builder /client /app/client

# Открываем порт HTTP
EXPOSE 8080

# Запускаем клиент
CMD ["./client"]