# Используем официальный образ Go
FROM golang:1.25-alpine AS builder

# Устанавливаем зависимости
RUN apk add --no-cache git

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы проекта
COPY go.mod go.sum ./
COPY proto/ proto/
COPY gen/ gen/
COPY cmd/server/main.go cmd/server/main.go

# Скачиваем зависимости
RUN go mod download

# Собираем приложение
RUN CGO_ENABLED=0 GOOS=linux go build -o /server cmd/server/main.go

# Используем легкий образ для финального изображения
FROM alpine:latest

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем собранное приложение
COPY --from=builder /server /app/server

# Открываем порт gRPC
EXPOSE 50051

# Запускаем сервер
CMD ["./server"]